// #include <sqlext.h>

#define SQLALLOCENVHANDLE(A) SQLAllocHandle(SQL_HANDLE_ENV, (void*)0, A)
#define SQLFREEENVHANDLE(A) SQLFreeHandle(SQL_HANDLE_ENV, A)
#define SQLENVGETDIAGREC(A,B,C,D,E,F,G) SQLGetDiagRec(SQL_HANDLE_ENV, A, B, C, D, E, F, G)

#define SQLALLOCDBCHANDLE(A,B) SQLAllocHandle(SQL_HANDLE_DBC, A, B)
#define SQLFREEDBCHANDLE(A) SQLFreeHandle(SQL_HANDLE_DBC, A)
#define SQLDBCGETDIAGREC(A,B,C,D,E,F,G) SQLGetDiagRec(SQL_HANDLE_DBC, A, B, C, D, E, F, G)

#define SQLALLOCSTMTHANDLE(A,B) SQLAllocHandle(SQL_HANDLE_STMT, A, B)
#define SQLFREESTMTHANDLE(A) SQLFreeHandle(SQL_HANDLE_STMT, A)
#define SQLSTMTGETDIAGREC(A,B,C,D,E,F,G) SQLGetDiagRec(SQL_HANDLE_STMT, A, B, C, D, E, F, G)
